更新.gitlab-ci.yml文件

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -20,4 +20,13 @@ compile:
   stage: build
   script:
     - npm run build
-
+check:
+  stage: test
+  script:
+    - |
+      if [[ ! -f dist/markdown-editor.js ]]; then
+        echo "failed!"
+      fi
+    -  
+      exit 1
+    
